#!/bin/bash

echo "🚁 Testing Ultra-Clean Sensor Topic Structure"
echo "=============================================="

echo ""
echo "Expected Topics (9 sensor types):"
echo "1. ✅ /PX4_Drone1/odom_local_ned   (nav_msgs/msg/Odometry)"
echo "2. ✅ /PX4_Drone1/global_gps       (sensor_msgs/msg/NavSatFix)" 
echo "3. ✅ /PX4_Drone1/imu              (sensor_msgs/msg/Imu)"
echo "4. ✅ /PX4_Drone1/environment      (airsim_interfaces/msg/Environment)"
echo "5. ✅ /PX4_Drone1/camera0/image    (sensor_msgs/msg/Image) - RViz2 WORKING!"
echo "6. ✅ /PX4_Drone1/camera0/camera_info (sensor_msgs/msg/CameraInfo)"
echo "7. 🚫 /PX4_Drone1/lidar0/points    (sensor_msgs/msg/PointCloud2) - Not in settings"
echo "8. ✅ /PX4_Drone1/mag              (sensor_msgs/msg/MagneticField)"
echo "9. ✅ /PX4_Drone1/baro             (sensor_msgs/msg/Range)"

echo ""
echo "Expected Services:"
echo "1. ✅ /PX4_Drone1/takeoff           (airsim_interfaces/srv/Takeoff)"
echo "2. ✅ /PX4_Drone1/land              (airsim_interfaces/srv/Land)"
echo "3. ✅ /PX4_Drone1/reset             (airsim_interfaces/srv/Reset)"

echo ""
echo "Expected Subscribers (Command Topics):"
echo "1. ✅ /PX4_Drone1/vel_cmd_body_frame  (airsim_interfaces/msg/VelCmd)"
echo "2. ✅ /PX4_Drone1/vel_cmd_world_frame (airsim_interfaces/msg/VelCmd)"

echo ""
echo "🔧 To test after rebuilding and launching:"
echo ""
echo "# Build the workspace"
echo "colcon build"
echo "source install/setup.bash"
echo ""
echo "# Launch with full sensor support"
echo "ros2 launch airsim_ros_pkgs rpc_dynamic_vehicles.launch.py"
echo ""
echo "# In another terminal, check topics:"
echo "ros2 topic list | grep -E '/(Droan|PX4_)'"
echo ""
echo "# Check camera feed (should show images if AirSim has cameras configured)"
echo "ros2 topic echo /Droan1/camera0/image --once"
echo ""
echo "# Check lidar data (should show point clouds if LiDAR is configured)"
echo "ros2 topic echo /Droan1/lidar0/points --once"
echo ""
echo "# Test individual vehicle control"
echo "ros2 service call /Droan1/takeoff airsim_interfaces/srv/Takeoff \"{wait_on_last_task: true}\""

echo ""
echo "🆕 = New topics/services that should now appear"
echo "✅ = Previously working topics/services"