# Get WSL2 vEthernet Adapter IP Address
# This script retrieves the stable Windows-side vEthernet (WSL) adapter IP
# and optionally writes it to environment files for Docker Compose

param(
    [switch]$WriteToEnv = $false,
    [string]$EnvFile = "../.env.wsl2",
    [switch]$Silent = $false,
    [switch]$JsonOutput = $false
)

function Write-Status {
    param([string]$Message)
    if (-not $Silent) {
        Write-Host $Message
    }
}

function Get-WSL2IP {
    try {
        # Get the vEthernet (WSL) adapter IP
        $wslAdapter = Get-NetIPAddress -InterfaceAlias "vEthernet (WSL)" -AddressFamily IPv4 -ErrorAction Stop
        
        if ($wslAdapter) {
            return $wslAdapter.IPAddress
        } else {
            throw "vEthernet (WSL) adapter found but no IPv4 address assigned"
        }
    }
    catch {
        # Fallback: Try alternative adapter names
        $alternativeNames = @("vEthernet (WSL (Hyper-V firewall))", "vEthernet (Default Switch)", "vEthernet (DockerNAT)")
        
        foreach ($name in $alternativeNames) {
            try {
                $adapter = Get-NetIPAddress -InterfaceAlias $name -AddressFamily IPv4 -ErrorAction SilentlyContinue
                if ($adapter) {
                    Write-Status "Warning: Using alternative adapter '$name' instead of 'vEthernet (WSL)'"
                    return $adapter.IPAddress
                }
            }
            catch {
                # Continue to next alternative
            }
        }
        
        # Last resort: Try to find any vEthernet adapter in the 172.x.x.1 range
        try {
            $vEthernetAdapters = Get-NetIPAddress -InterfaceAlias "vEthernet*" -AddressFamily IPv4 -ErrorAction SilentlyContinue
            foreach ($adapter in $vEthernetAdapters) {
                if ($adapter.IPAddress -match "^172\.\d+\.\d+\.1$") {
                    Write-Status "Warning: Using detected vEthernet adapter with IP $($adapter.IPAddress)"
                    return $adapter.IPAddress
                }
            }
        }
        catch {
            # No suitable adapter found
        }
        
        throw "Could not find WSL2 vEthernet adapter. Ensure WSL2 is running and Docker Desktop is installed."
    }
}

# Main execution
try {
    $wsl2IP = Get-WSL2IP
    
    if ($JsonOutput) {
        # Output as JSON for programmatic consumption
        $output = @{
            success = $true
            ip = $wsl2IP
            timestamp = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
        }
        Write-Output (ConvertTo-Json $output)
    }
    else {
        Write-Status "========================================="
        Write-Status " WSL2 vEthernet Adapter IP Detection"
        Write-Status "========================================="
        Write-Status ""
        Write-Status "Detected WSL2 IP: $wsl2IP"
        Write-Status ""
        
        if ($WriteToEnv) {
            # Create environment file content
            $envContent = @"
# WSL2 vEthernet Adapter Configuration
# Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# This file is auto-generated by get-wsl2-ip.ps1

# Primary WSL2 Bridge IP (Windows-side vEthernet adapter)
WSL2_IP=$wsl2IP

# AirSim host configuration
AIRSIM_HOST_IP=$wsl2IP

# PX4 simulation host configuration
PX4_SIM_HOSTNAME=$wsl2IP

# Optional: Override the default WSL2 detector behavior
SKIP_WSL2_DETECTOR=true
"@
            
            # Ensure directory exists
            $envPath = Join-Path $PSScriptRoot $EnvFile
            $envDir = Split-Path $envPath -Parent
            if (-not (Test-Path $envDir)) {
                New-Item -ItemType Directory -Path $envDir -Force | Out-Null
            }
            
            # Write to file
            Set-Content -Path $envPath -Value $envContent -Encoding UTF8
            
            Write-Status "Configuration written to: $envPath"
            Write-Status ""
            Write-Status "To use this configuration:"
            Write-Status "1. From docker directory: docker-compose --env-file .env.wsl2 -f docker-compose-master.yml up"
            Write-Status "2. Or with MNSTEVV CLI: mnstevv up --airsim-host $wsl2IP --px4-sim-host $wsl2IP"
            Write-Status "3. Or merge into your main .env file"
        }
        else {
            Write-Status "To write to environment file, use: .\get-wsl2-ip.ps1 -WriteToEnv"
            Write-Status ""
            Write-Status "Manual usage:"
            Write-Status "  export AIRSIM_HOST_IP=$wsl2IP"
            Write-Status "  export PX4_SIM_HOSTNAME=$wsl2IP"
        }
    }
    
    # Exit with success
    exit 0
}
catch {
    if ($JsonOutput) {
        $output = @{
            success = $false
            error = $_.Exception.Message
            timestamp = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
        }
        Write-Output (ConvertTo-Json $output)
    }
    else {
        Write-Status "ERROR: $($_.Exception.Message)"
        Write-Status ""
        Write-Status "Troubleshooting:"
        Write-Status "1. Ensure WSL2 is installed and running"
        Write-Status "2. Check if Docker Desktop is running"
        Write-Status "3. Run 'wsl --status' to verify WSL2 is active"
        Write-Status "4. Try running this script as Administrator"
    }
    
    # Exit with error
    exit 1
}